### ISSUE TITLE
Datepicker not popping up 

### ISSUE THREAD

**Issue by waseemm1975** [tommcfarlin/WordPress-jQuery-Date-Picker#1]
I installed a fresh new wp and installed the plugin once i activated and go to add new post it just shows The Date and when i click the text box nothing pops up...

**Comment by tommcfarlin** [comment]
Can you give a little bit more information for me? This is a bit of an old repository and it was tested with an old version of WordPress. 
- Are there errors in your browser console? 
- What are the recreation steps so that I can reproduce this locally?

**Comment by waseemm1975** [comment]
yea im sorry for being vague. You can try it online
iqamah.org/wp
admin
pass

**Comment by tommcfarlin** [comment]
I deleted your last comment because it's not a good idea to share your domain and your username and password in a public forum like GitHub.

Rather than giving me the login to your site, can you please follow the two points above? It'll help me to try to resolve this issue.

**Comment by waseemm1975** [comment]
yea i was hesitate about putting that info but put because it was a temp site.
anyways...
i see no errors.
I just installed fresh new wordpress and installed plugin.

**Comment by tommcfarlin** [comment]
Gotcha - thanks for the info. I'll look into this as soon as possible. It may be a while as I have other contracts on which I'm working, but this won't be falling off my radar.

Thanks!

**Comment by tommcfarlin** [comment]
I'm unable to reproduce this issue and there's no errors appearing in the console. 

Culprits for why it's not working could be the theme or another plugin. It may also be the browser, but that's not likely given that I've tested it in the major versions of the grade-A browsers.

If you can provide more details and verify that it's _not_ your theme or _any other_ plugin, then feel free to open this issue again.

![screen shot 2015-07-31 at 3 28 13 pm](https://cloud.githubusercontent.com/assets/132166/9015718/d61b6b96-3798-11e5-9243-5bd724ffbec9.png)
